### PR TITLE
Add contributing file with pre-commit instructions

### PR DESCRIPTION
**Pull request by IanEdington**
Documenting what I'm doing to develop against git-pile

### CODE REVIEW

**Comment by IanEdington** [comment]
😬 I was expecting this to go against my fork. oops 😄

**Comment by keith** [comment]
Fine with me if you want to add something like this!

**Comment by IanEdington** [comment]
Sounds good. I'm going to be working on a few other things that I'll submit separately and was going to update this PR with anything else I find. I'm happy to wait or merge and summit further changes in the future.

**Comment by keith** [comment]
feel free to reopen when you're ready!

**Comment by IanEdington** [comment]
Thanks Keith!

**Pull request closed without merging**
